# sim launch scenario and rocket configuration

time_step = 0.01 # seconds

# one entry per rocket
[[launch]]
origin_lat = 48.209
origin_lon = -101.406
target_lat = 53.9
target_lon = 43.3

[rocket]
radius = 0.835
drag_coefficient = 0.0

# ROCKET

[[rocket.stage]]
id = 1
dry_mass = 2292.0
fuel_mass = 20938.0
isp = 267.0
length = 7.49
com_distance = 3.75
max_thrust = 903692.0
engine_distance = 7.49
gimbal_range_deg = 5.0

[[rocket.stage]]
id = 2
dry_mass = 795.0
fuel_mass = 6237.0
isp = 288.0
length = 4.12
com_distance = 2.06
max_thrust = 270421.0
engine_distance = 4.12
gimbal_range_deg = 5.0

[[rocket.stage]]
id = 3
dry_mass = 1500.0
fuel_mass = 3306.0
isp = 285.0
length = 6.59
com_distance = 3.3
max_thrust = 156070.0
engine_distance = 6.59
gimbal_range_deg = 4.0
rcs_max_moment = [100.0, 100.0, 100.0]
